; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Tue Jun 16 2020 20:13:31 GMT-0500 (Central Daylight Time)
M561                      ; clear any bed transform
M98 P"macros/Level.g"     ; level the bed via Z-screws
G29                       ; probe the bed and enable compensation
G1 Z5 F720                ; Lift a little off Z
G1 X0 Y0 F15000           ; Go home


