; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Tue Jun 16 2020 20:13:32 GMT-0500 (Central Daylight Time)
G91                  ; relative positioning
G1 H2 Z5 F3000       ; lift Z relative to current position
G1 H1 Z-215.15 F3000 ; move Z down until the endstop is triggered
G892                 ; set Z position to probe trigger height (see G892.g)
G90
