; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Tue Jun 16 2020 20:13:33 GMT-0500 (Central Daylight Time)
; Wait for set temperatures to be reached
M116 P0
M703        ; load filament configuration
